### ISSUE TITLE
Permita modificar los datos de los empleados existentes

### ISSUE THREAD

**Issue by JorgeMedranoNovas** [JorgeMedranoNovas/Registro_De_Emplados-#26]
Como: encargada de recursos humanos
Quiero: que me permita modificar los datos de los empleados existentes
Para: actualizar su información. 

**Cristerios de aceptacion**
-Solo se le permitira actualizar datos a los usuarios con rango de admin
-le permitria editar todos los datos del empleando(nombre, apellido, fecha, nomina y vacaciones)

**Comment by moiszr** [comment]
Esta funcionalidad fue realizada
